This is a testharness.js-based test.
PASS Cache.add called with no arguments 
PASS Cache.add called with relative URL specified as a string 
PASS Cache.add called with non-HTTP/HTTPS URL 
PASS Cache.add called with Request object 
PASS Cache.add called with POST request 
PASS Cache.add called with Request object with a used body 
PASS Cache.add with request that results in a status of 404 
PASS Cache.add with request that results in a status of 500 
FAIL Cache.addAll with no arguments promise_test: Unhandled rejection with value: object "TypeError: cache.addAll is not a function"
FAIL Cache.addAll with a mix of valid and undefined arguments promise_test: Unhandled rejection with value: object "TypeError: cache.addAll is not a function"
FAIL Cache.addAll with string URL arguments promise_test: Unhandled rejection with value: object "TypeError: cache.addAll is not a function"
FAIL Cache.addAll with Request arguments promise_test: Unhandled rejection with value: object "TypeError: cache.addAll is not a function"
FAIL Cache.addAll with a mix of succeeding and failing requests promise_test: Unhandled rejection with value: object "TypeError: cache.addAll is not a function"
Harness: the test ran to completion.

